[project]
license = "Apache-2.0"
org-name = "wso2"
version = "0.8.13"
authors = ["WSO2"]
homepage = "https://wso2.com/"
repository = "https://github.com/wso2-ballerina/package-twilio"
keywords = ["twilio", "sms", "call", "otp"]